num1 = eval(input())
num2 = eval(input())
num3 = eval(input())
num4 = eval(input())
print(f'( {num1} , {num2} )')
print(f'( {num3} , {num4} )')
print(f'Distance = {((num1-num3)**2+(num2-num4)**2)**0.5:.4f}')
